FROM python:3.10-slim
RUN apt-get update && apt-get install -y gcc libpq-dev unar unrar-free unzip curl && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY backend/ ./backend/
COPY logic/ ./logic/
ENV PYTHONPATH=/app/backend:/app/logic
WORKDIR /app/backend
